app1/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib import admin
from . import views
app_name = 'app1'

urlpatterns = [
    url(r'^$', views.IndexView, name='index'),
    url(r'^add/', views.Directory_Add, name='add'),
    url(r'^(?P<slug>[-\w]+)/edit', views.Directory_Detail, name='edit'),
    url(r'^search/$', views.submit_search, name='number_search'),
    url(r'^api/get_names/', views.get_names, name='get_names'),



]

directory/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from app1.api import DirectoryResource

directory_resource = DirectoryResource()

urlpatterns = [
    url(r'^app1/', include('app1.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(directory_resource.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
]

app1/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse

from django.db import models

class Directory(models.Model):
    name = models.CharField(max_length=25)
    number = models.CharField(max_length=(10),unique=True)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwarge):
    	name_number=str(self.name) + " " + str(self.number)
        self.slug=slugify(name_number)
        super(Directory,self).save(*args, **kwarge)

    def get_absolute_url(self):
        return reverse('app1:edit', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


# Create your models here.

app1/forms.py
from django import forms
from .models import Directory

class DirectoryForm(forms.ModelForm):
    class Meta:
    	model=Directory
    	fields=['name','number']


    def clean_number(self):
        data = self.cleaned_data['number']
        print data
        if len(data) <10:
            raise forms.ValidationError("Invalid phone number ")

        # Always return the cleaned data, whether you have changed it or
        # not.
        return data
       

app1/views.py
from django.shortcuts import render
from django.views import generic
from .models import Directory
from .forms import DirectoryForm
from django.shortcuts import redirect
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
import json 
from django.http import HttpResponse


def IndexView(request):
    model = Directory
    queryset=Directory.objects.all()
    template_name = 'app1/index.html'
    form=DirectoryForm()

    query= request.GET.get("q")
    if query:
    	queryset=queryset.filter(
    		Q(name__icontains=query) | 
    	    Q(number__icontains=query)
    	    )

    context= {
    	"objects_list": queryset,
    	"form": form
    }
    return render(request,"app1/index.html",context)

def submit_search(request):
	numbers = []
	search_text = "" 
	if(request.method == "GET"):
		search_text = request.GET.get("number_search_text", "")
	number_results = []
	if(search_text != ""):
		number_results = Directory.objects.filter(Q(name__icontains=search_text) | Q(number__icontains=search_text))
	else:
		number_results = Directory.objects.all()
	context= {
    	"objects_list": number_results,
    	"search_text": search_text
    }
	return  render_to_response("app1/search_results__html_snippet.html",context)

def Directory_Add(request):
	form=DirectoryForm(request.POST or None)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
		messages.success(request,"Record successfully added!")
		#print request
	else:
		form = DirectoryForm()
	#return redirect("app1:index")
	number_results = Directory.objects.all()
	context= {
    	"objects_list": number_results,
    }
	return  render_to_response("app1/search_results__html_snippet.html",context)
	#return  render_to_response(request,"app1/search_results__html_snippet.html",context)

def Directory_Detail(request,slug=None):
	instance=get_object_or_404(Directory,slug=slug)
	form=DirectoryForm(request.POST or None, instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
		messages.success(request,"Record Updated!")
		return redirect("app1:index")

	context= {
	"instance":instance,
	"form":form,
	}
	return render(request,"app1/Directory_Detail.html",context)

def get_names(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        numbers = Directory.objects.filter(Q(name__icontains=q))[:20]
        results = []
        for number in numbers:
            number_json = {}
            number_json['id'] = number.id
            print number.id
            number_json['label'] = number.name
            print number.name
            number_json['value'] = number.name
            results.append(number_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)





# Create your views here.

app1/templates/app1/Directory_Detail.html
{% extends 'app1/base.html' %}
{% block content %}



<form action="" method="post">
   {% csrf_token %}
   {{ form }}
    <input type="submit" value="Update" class="btn btn-primary">
</form>

{% endblock %}

app1/templates/app1/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/starter-template/starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script> -->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link type="text/css" href="{% static 'app1/table.css' %}" rel="stylesheet">



    <!-- <script type='text/javascript' src="{% static 'app1/number_ajax_main.js' %}"></script> --> 
  
    <script>
    $(document).ready(function()  {
    jQuery('.ajaxform').submit( function(e) {
    //jQuery('#number_search_text').keyup(function(e){
    e.preventDefault();
    //alert("in ajax");
  
    var searchText = $('#number_search_text').val();
    //alert(searchText);
    var config = {
            url     : $(this).attr('action'),
            type    : $(this).attr('method'),
            data: {
            'number_search_text' : searchText,
          },
          dataType: 'html',
          success: processServerResponse

        };
        $.ajax(config);
     });
     var processServerResponse = function(sersverResponse_data, textStatus_ignored,
                        jqXHR_ignored)  {
      //alert("sersverResponse_data='" + sersverResponse_data + "', textStatus_ignored='" + textStatus_ignored + "', jqXHR_ignored='" + jqXHR_ignored + "'");
      //$('#number_search_results').load(sersverResponse_data);
      $('#number_search_results').html(sersverResponse_data);
      //$('#success').append('<li class="alert alert-success">Record successfully added!</li>');
      $('#addbutton').trigger("reset")
    };

    $("#addbutton").submit(function(e){
        //alert("ajax add")
        e.preventDefault();
         dataString = $("#addbutton").serialize();

         $.ajax({
           type: $(this).attr('method'),
           url: $(this).attr('action'),
           data: dataString,

           dataType: "html",
           success: processServerResponse

          });
    });

      $("#number_search_text").autocomplete({
    source: "api/get_names/",
    minLength: 2,
    select: function(event,ui) {
      if(ui.item){
        $('#number_search_text').val(ui.item.value);
      }
      $('.ajaxform').submit();
    }
  });


 });
 </script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Directory</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            
          </ul>
        </div><!--/.nav-collapse -->

      </div>

    </nav>
<!--     <div class="container">
   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} 
</div> -->

    <div class="container" id="maindiv">
      <br>
 {% block content %}{% endblock content %}
      <div class="starter-template">
   
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
<!-- 
    <script>
$(document).ready(function(){
    $("tr").click(function(){
        $(this).hide();
    });
});
</script>
 -->

  </body>
</html>

app1/templates/app1/index.html
{% extends 'app1/base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<form action="{% url 'app1:add' %}" method="post" id="addbutton">
   {% csrf_token %}
   {{ form }}
    <input type="submit" value="Add" class="btn btn-primary">
</form>


<br>

<!--
<form action="{% url 'app1:number_search' %}" method='GET' class='ajaxform' id="ajaxform" >
   <input type='text' id='number_search_text' name='search_text' placeholder="Search for...">
   <input type="submit" value="Search" >
</form>
-->
<form action="{% url 'app1:number_search' %}" method='GET' class='ajaxform' id="ajaxform" >
<div class="col-lg-12">
  <div class="input-group">
    <input type='text' id='number_search_text' name='search_text' placeholder="Search for...">
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit">Go!</button>
    </span>
  </div>
</div>
</form>




<!--
<form method="GET" action="" >
<div class="col-lg-12">
    <div class="input-group">

      <input type="text" name="q" class="form-control" placeholder="Search for..." value='{{ request.GET.q }}'>
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>
    </div><!-- /input-group 
  </div><!-- /.col-lg-6 
</form> -->
  <br>
<br>


<div id="number_search_results">

<div class="panel panel-default">
  <!-- Default panel contents -->



  <!-- Table -->
  <table class="table table-striped">
    <thead>
    	<tr>
    		<th>#ID</th>

    		<th>#Name</th>
    		<th>#Number</th>
    	</tr>
    </thead>
    <tbody>
  

{% if objects_list %}

    
    {% for object in objects_list %}
    <tr>
    
     <td> <a href="{{ object.get_absolute_url }}"> {{ object.id }} </td> </a>
     <td>  {{ object.name }} </td>
     <td>	{{object.number}} </td>
 </tr>
    {% endfor %}
    
    </tbody>
    </table>
</div>

{% else %}
    <p>No Names and number available.</p>
{% endif %}

</div>
{% endblock %}

app1/templates/app1/search_results__html_snippet.html
<!DOCTYPE html>
<div class="panel panel-default">
  <!-- Default panel contents -->


<table class="table table-striped">
    <thead>
    	<tr>
    		<th>#ID</th>

    		<th>#Name</th>
    		<th>#Number</th>
    	</tr>
    </thead>
    <tbody>
  

{% if objects_list %}

    
    {% for object in objects_list %}
    <tr>
    
     <td> <a href="{{ object.get_absolute_url }}"> {{ object.id }} </td> </a>
     <td>  {{ object.name }} </td>
     <td>	{{object.number}} </td>
 </tr>
    {% endfor %}
    
    </tbody>
    </table>
</div>

{% else %}
    <p>No Names and number available.</p>
{% endif %}